[project]
name = "ghtriage"
version = "0.1.0"
description = "A local, queryable snapshot of a GitHub repository's issues, pull requests, and comments. Built for AI coding agents to assist with project management."
readme = "README.md"
authors = [
    { name = "Jay Qi", email = "jayqi.opensource@gmail.com" },
]
maintainers = [
    { name = "Jay Qi", email = "jayqi.opensource@gmail.com" },
    { name = "DrivenData", email = "info@drivendata.org" },
]
license = "MIT"
license-files = ["LICENSE"]
keywords = [
  "github",
  "issues",
  "pull requests",
  "project management",
]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Bug Tracking",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.10"
dependencies = [
    "dlt[duckdb]>=1.0,<2",
    "duckdb>=1.2",
    "tomli>=2.0.1; python_version < '3.11'",
    "tomlkit>=0.14.0",
]

[project.urls]
"Repository" = "https://github.com/drivendataorg/ghtriage"
"Bug Tracker" = "https://github.com/drivendataorg/ghtriage/issues"

[project.scripts]
ghtriage = "ghtriage:main"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff",
    "zizmor",
    { include-group = "tests" },
    { include-group = "typecheck" },
]
tests = [
    "coverage",
    "pytest-cov",
    "pytest",
]
typecheck = [
    "ty",
]
vspect = [
    "vspect",
]

## TOOLS

[tool.uv]
exclude-newer = "7 days"

[tool.ruff]
line-length = 99
src = ["src/ghtriage/**/*.py", "tests/**/*.py"]

[tool.ruff.lint]
select = [
  "E", # Pyflakes
  "F", # Pycodestyle
  "I", # isort
]
unfixable = ["F"]

[tool.ruff.lint.isort]
known-first-party = ["ghtriage"]
force-sort-within-sections = true

[tool.ty.src]
include = ["src"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=ghtriage --cov-report=term --cov-report=html --cov-report=xml"
testpaths = ["tests"]

[tool.coverage.run]
source = ["ghtriage"]
# debug = ["pathmap"]  # Useful if path mapping isn't working as expected

[tool.coverage.paths]
ghtriage = [
  "src/ghtriage/",
  "*/site-packages/ghtriage/"
]
